name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches: [docopts-go, master]

jobs:
  ci:
    name: CI - Go ${{ matrix.go-version }}, ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ["1.14"]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        # cache: true # TODO: cache needs path to go.sum per https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
    - name: Install
      run: |
        bash --version ; type bash
        # hack for speedup on mac build with our own bash5
        ./ci/get_bash5_macos.sh
        ./ci/get_bats-core.sh
        go get github.com/docopt/docopt-go
        # get our official repos too
        go get github.com/docopt/docopts
    - name: Test
      run: make test

      # For debugging, create reverse SSH tunnel (this should be run on failure too)
      # - name: Debug
      #   if: runner.os == "macOS"
      #   run: bash -x ./ci/reverse_ssh_tunnel.sh
